TYPE_data_collection_documents = [{"rec_id"=>"collection","label_fr"=>"Collection","label_en"=>"Collection","value_ddi"=>"Collection"},
{"rec_id"=>"Dataset","label_fr"=>"Jeu de données","label_en"=>"Dataset","value_ddi"=>"Dataset"},
{"rec_id"=>"StillImage","label_fr"=>"Image","label_en"=>"Still image","value_ddi"=>"Still image"},
{"rec_id"=>"InteractiveResource","label_fr"=>"Ressource web","label_en"=>"Interactive resource","value_ddi"=>"Interactive resource"},
{"rec_id"=>"MovingImage","label_fr"=>"Enregistrement vidéo","label_en"=>"Moving image","value_ddi"=>"Moving image"},
{"rec_id"=>"physicalObject","label_fr"=>"Objet","label_en"=>"Physical object","value_ddi"=>"Physical object"},
{"rec_id"=>"Software","label_fr"=>"Élément logiciel","label_en"=>"Software","value_ddi"=>"Software"},
{"rec_id"=>"Sound","label_fr"=>"Enregistrement audio","label_en"=>"Sound","value_ddi"=>"Sound"},
{"rec_id"=>"Text","label_fr"=>"Document textuel","label_en"=>"Text","value_ddi"=>"Text"}]


TYPE_speaker_role = [{"rec_id"=>"speaker","label_fr"=>"Enquêté","label_en"=>"Speaker"},
{"rec_id"=>"investigator","label_fr"=>"Enquêteur","label_en"=>"Investigator"},
{"rec_id"=>"protagonist","label_fr"=>"Protagoniste","label_en"=>"Protagonist"}]


TYPE_analysis_types = [{"rec_id"=>"interpretative","label_fr"=>"Analyse interprétative","label_en"=>"Interpretative analysis","value_ddi"=>"Interpretative analysis"},
{"rec_id"=>"typilogical","label_fr"=>"Analyse typologique","label_en"=>"Typological analysis","value_ddi"=>"Typological analysis"},
{"rec_id"=>"lexicometric","label_fr"=>"Analyse lexicométrique","label_en"=>"Lexicometric analysis","value_ddi"=>"Lexicometric analysis"},
{"rec_id"=>"coding","label_fr"=>"Analyse par codification","label_en"=>"Codification analysis","value_ddi"=>"Codification analysis"},
{"rec_id"=>"qca","label_fr"=>"Analyse QCA","label_en"=>"QCA analysis","value_ddi"=>"QCA analysis"},
{"rec_id"=>"other","label_fr"=>"Autre","label_en"=>"Other","value_ddi"=>"Other"}]


TYPE_analysis_anonymization = [{"rec_id"=>"yes","label_fr"=>"Oui","label_en"=>"Yes"},
{"rec_id"=>"no","label_fr"=>"Non","label_en"=>"No"},
{"rec_id"=>"partially","label_fr"=>"Partiellement","label_en"=>"Partially"}]


TYPE_analysis_has_transcription = [{"rec_id"=>"yes","label_fr"=>"Oui","label_en"=>"Yes"},
{"rec_id"=>"no","label_fr"=>"Non","label_en"=>"No"},
{"rec_id"=>"unknow","label_fr"=>"Ne sait pas","label_en"=>"Unknow"}]


TYPE_archive_agreememt = [{"rec_id"=>"yes","label_fr"=>"Oui","label_en"=>"Yes"},
{"rec_id"=>"no","label_fr"=>"Non","label_en"=>"No"},
{"rec_id"=>"partially","label_fr"=>"Partiellement","label_en"=>"Partially"},
{"rec_id"=>"unknown","label_fr"=>"Ne sait pas","label_en"=>"Unknown"}]


TYPE_archive_accessed = [{"rec_id"=>"yes","label_fr"=>"Oui","label_en"=>"Yes"},
{"rec_id"=>"no","label_fr"=>"Non","label_en"=>"No"},
{"rec_id"=>"partially","label_fr"=>"Partiellement","label_en"=>"Partially"}]

TYPE_interviewers_unknown = [{"rec_id"=>"yes","label_fr"=>"Oui","label_en"=>"Yes"},
{"rec_id"=>"no","label_fr"=>"Non","label_en"=>"No"},
{"rec_id"=>"unknow","label_fr"=>"Ne sait pas","label_en"=>"Unknow"}]

TYPE_data_collection_has_media = [{"rec_id"=>"yes","label_fr"=>"Oui","label_en"=>"Yes"},
{"rec_id"=>"no","label_fr"=>"Non","label_en"=>"No"},
{"rec_id"=>"unknow","label_fr"=>"Ne sait pas","label_en"=>"Unknow"}]

TYPE_archive_consentement = [{"rec_id"=>"yes","label_fr"=>"Oui","label_en"=>"Yes"},
{"rec_id"=>"no","label_fr"=>"Non","label_en"=>"No"},
{"rec_id"=>"partially","label_fr"=>"Partiellement","label_en"=>"Partially"},
{"rec_id"=>"unknow","label_fr"=>"Ne sais pas","label_en"=>"Unknow"},
{"rec_id"=>"postponed","label_fr"=>"Réserve sa réponse","label_en"=>"Postponed"}]


TYPE_archive_preservation_level = [{"rec_id"=>"good","label_fr"=>"Bon","label_en"=>"Good"},
{"rec_id"=>"acceptable","label_fr"=>"Moyen","label_en"=>"Acceptable"},
{"rec_id"=>"bad","label_fr"=>"Mauvais","label_en"=>"Bad"}]


TYPE_archive_arrangement_level = [{"rec_id"=>"ordered","label_fr"=>"Classé","label_en"=>"Ordered","value_ddi"=>"Ordered"},
{"rec_id"=>"partially_ordered","label_fr"=>"Partiellement classé","label_en"=>"Partially ordered","value_ddi"=>"Partially ordered"},
{"rec_id"=>"miscellaneous","label_fr"=>"Hétérogéne","label_en"=>"Miscellaneous","value_ddi"=>"Miscellaneous"},
{"rec_id"=>"bulk","label_fr"=>"Vrac","label_en"=>"Bulk","value_ddi"=>"Bulk"}]

TYPE_data_collection_time_dimen = [{"rec_id"=>"one_time_interview","label_fr"=>"Entretien unique","label_en"=>"One time interview","value_ddi"=>"One time interview"},
{"rec_id"=>"repeated_interview","label_fr"=>"Entretien répété","label_en"=>"Repeated interview","value_ddi"=>"Repeated interview"},
{"rec_id"=>"one_time_observation","label_fr"=>"Observation ponctuelle","label_en"=>"One-time observation","value_ddi"=>"One-time observation"},
{"rec_id"=>"repeted_observation","label_fr"=>"Observation systématique","label_en"=>"Repeted observation","value_ddi"=>"Repeted observation"},
{"rec_id"=>"other","label_fr"=>"Autre","label_en"=>"Other","value_ddi"=>"Other"}]

TYPE_data_collection_modes = [{"rec_id"=>"interview","label_fr"=>"Enquête par entretien","label_en"=>"Interview","value_ddi"=>"Interview"},
{"rec_id"=>"observation","label_fr"=>"Enquête par observation","label_en"=>"Observation","value_ddi"=>"Observation"},
{"rec_id"=>"content_analysis","label_fr"=>"Enquête par analyse de documents","label_en"=>"Content analysis","value_ddi"=>"Content analysis"},
{"rec_id"=>"questionnaire","label_fr"=>"Enquête par questionnaire","label_en"=>"Questionnaire","value_ddi"=>"Questionnaire"},
{"rec_id"=>"intervention","label_fr"=>"Observation sociologique","label_en"=>"Intervention","value_ddi"=>"Intervention"},
{"rec_id"=>"other","label_fr"=>"Autre","label_en"=>"Other","value_ddi"=>"Other"}]


TYPE_location_of_units_of_obser = [{"rec_id"=>"international","label_fr"=>"International","label_en"=>"International","value_ddi"=>"International"},
{"rec_id"=>"national","label_fr"=>"National","label_en"=>"National","value_ddi"=>"National"},
{"rec_id"=>"infra_national","label_fr"=>"Infra-national","label_en"=>"Infra-national","value_ddi"=>"Infra-national"}]

TYPE_data_collection_methods = [{"rec_id"=>"questionnaire","label_fr"=>"Questionnaire","label_en"=>"Questionnaire","value_ddi"=>"Questionnaire"},
{"rec_id"=>"directiveItw","label_fr"=>"Guide d'entretien directif","label_en"=>"Structured interview guide","value_ddi"=>"Structured interview guide"},
{"rec_id"=>"semi_directive_intertview","label_fr"=>"Guide d'entretien semi-structuré","label_en"=>"Semi-structured interview guide","value_ddi"=>"Semi-structured interview guide"},
{"rec_id"=>"none_directive_interview","label_fr"=>"Consigne (entretien non-directif)","label_en"=>"Non-structured interview instructions","value_ddi"=>"Non-structured interview instructions"},
{"rec_id"=>"participant_observation","label_fr"=>"Protocole d'expérimentation","label_en"=>"Expérimental protocole","value_ddi"=>"Expérimental protocole"},
{"rec_id"=>"experimentation","label_fr"=>"Carnet d'enquête","label_en"=>"Survey book","value_ddi"=>"Survey book"},
{"rec_id"=>"content_analysis","label_fr"=>"Analyse documentaire","label_en"=>"Document analysis","value_ddi"=>"Document analysis"},
{"rec_id"=>"other","label_fr"=>"Autre","label_en"=>"Other","value_ddi"=>"Other"}]








TYPE_countries = [{"rec_id\nISO 3166 alpha2"=>"AD","label_fr"=>"Andorra","label_en"=>"Andorre"},
{"rec_id\nISO 3166 alpha2"=>"AE","label_fr"=>"United Arab Emirates","label_en"=>"Émirats Arabes Unis"},
{"rec_id\nISO 3166 alpha2"=>"AF","label_fr"=>"Afghanistan","label_en"=>"Afghanistan"},
{"rec_id\nISO 3166 alpha2"=>"AG","label_fr"=>"Antigua and Barbuda","label_en"=>"Antigua et Barbuda"},
{"rec_id\nISO 3166 alpha2"=>"AI","label_fr"=>"Anguilla","label_en"=>"Anguilla"},
{"rec_id\nISO 3166 alpha2"=>"AL","label_fr"=>"Albania","label_en"=>"Albanie"},
{"rec_id\nISO 3166 alpha2"=>"AM","label_fr"=>"Armenia","label_en"=>"Arménie"},
{"rec_id\nISO 3166 alpha2"=>"AN","label_fr"=>"Netherlands Antilles","label_en"=>"Antilles néerlandaises"},
{"rec_id\nISO 3166 alpha2"=>"AO","label_fr"=>"Angola","label_en"=>"Angola"},
{"rec_id\nISO 3166 alpha2"=>"AQ","label_fr"=>"Antarctica","label_en"=>"Antarctique"},
{"rec_id\nISO 3166 alpha2"=>"AR","label_fr"=>"Argentina","label_en"=>"Argentine"},
{"rec_id\nISO 3166 alpha2"=>"AS","label_fr"=>"American Samoa","label_en"=>"Samoa américaines"},
{"rec_id\nISO 3166 alpha2"=>"AT","label_fr"=>"Austria","label_en"=>"Autriche"},
{"rec_id\nISO 3166 alpha2"=>"AU","label_fr"=>"Australia","label_en"=>"Australie"},
{"rec_id\nISO 3166 alpha2"=>"AW","label_fr"=>"Aruba","label_en"=>"Aruba"},
{"rec_id\nISO 3166 alpha2"=>"AX","label_fr"=>"Åland islands","label_en"=>"Åland, îles"},
{"rec_id\nISO 3166 alpha2"=>"AZ","label_fr"=>"Azerbaijan","label_en"=>"Azerbaïdjan"},
{"rec_id\nISO 3166 alpha2"=>"BA","label_fr"=>"Bosnia and Herzegovina","label_en"=>"Bosnie-Herzégovine"},
{"rec_id\nISO 3166 alpha2"=>"BB","label_fr"=>"Barbados","label_en"=>"Barbade"},
{"rec_id\nISO 3166 alpha2"=>"BD","label_fr"=>"Bangladesh","label_en"=>"Bangladesh"},
{"rec_id\nISO 3166 alpha2"=>"BE","label_fr"=>"Belgium","label_en"=>"Belgique"},
{"rec_id\nISO 3166 alpha2"=>"BF","label_fr"=>"Burkina Faso","label_en"=>"Burkina Faso"},
{"rec_id\nISO 3166 alpha2"=>"BG","label_fr"=>"Bulgaria","label_en"=>"Bulgarie"},
{"rec_id\nISO 3166 alpha2"=>"BH","label_fr"=>"Bahrain","label_en"=>"Bahreïn"},
{"rec_id\nISO 3166 alpha2"=>"BI","label_fr"=>"Burundi","label_en"=>"Burundi"},
{"rec_id\nISO 3166 alpha2"=>"BJ","label_fr"=>"Benin","label_en"=>"Bénin"},
{"rec_id\nISO 3166 alpha2"=>"BM","label_fr"=>"Bermuda","label_en"=>"Bermudes"},
{"rec_id\nISO 3166 alpha2"=>"BN","label_fr"=>"Brunei Darussalam","label_en"=>"Brunei"},
{"rec_id\nISO 3166 alpha2"=>"BO","label_fr"=>"Bolivia","label_en"=>"Bolivie"},
{"rec_id\nISO 3166 alpha2"=>"BR","label_fr"=>"Brazil","label_en"=>"Brésil"},
{"rec_id\nISO 3166 alpha2"=>"BS","label_fr"=>"Bahamas (The)","label_en"=>"Bahamas"},
{"rec_id\nISO 3166 alpha2"=>"BT","label_fr"=>"Bhutan","label_en"=>"Bhoutan"},
{"rec_id\nISO 3166 alpha2"=>"BV","label_fr"=>"Bouvet Island","label_en"=>"Île Bouvet"},
{"rec_id\nISO 3166 alpha2"=>"BW","label_fr"=>"Botswana","label_en"=>"Botswana"},
{"rec_id\nISO 3166 alpha2"=>"BY","label_fr"=>"Belarus","label_en"=>"Bélarus"},
{"rec_id\nISO 3166 alpha2"=>"BZ","label_fr"=>"Belize","label_en"=>"Belize"},
{"rec_id\nISO 3166 alpha2"=>"CA","label_fr"=>"Canada","label_en"=>"Canada"},
{"rec_id\nISO 3166 alpha2"=>"CC","label_fr"=>"Cocos (Keeling) Islands","label_en"=>"Îles Cocos"},
{"rec_id\nISO 3166 alpha2"=>"CD","label_fr"=>"Congo, the Democratic Republic of the","label_en"=>"Congo-Kinshasa"},
{"rec_id\nISO 3166 alpha2"=>"CF","label_fr"=>"Central African Republic (The)","label_en"=>"Centrafrique"},
{"rec_id\nISO 3166 alpha2"=>"CG","label_fr"=>"Congo","label_en"=>"Congo"},
{"rec_id\nISO 3166 alpha2"=>"CH","label_fr"=>"Switzerland","label_en"=>"Suisse"},
{"rec_id\nISO 3166 alpha2"=>"CI","label_fr"=>"Ivory Coast","label_en"=>"Côte d'Ivoire"},
{"rec_id\nISO 3166 alpha2"=>"CK","label_fr"=>"Cook Islands","label_en"=>"Cook, îles"},
{"rec_id\nISO 3166 alpha2"=>"CL","label_fr"=>"Chile","label_en"=>"Chili"},
{"rec_id\nISO 3166 alpha2"=>"CM","label_fr"=>"Cameroon","label_en"=>"Cameroun"},
{"rec_id\nISO 3166 alpha2"=>"CN","label_fr"=>"China","label_en"=>"Chine"},
{"rec_id\nISO 3166 alpha2"=>"CO","label_fr"=>"Colombia","label_en"=>"Colombie"},
{"rec_id\nISO 3166 alpha2"=>"CR","label_fr"=>"Costa Rica","label_en"=>"Costa Rica"},
{"rec_id\nISO 3166 alpha2"=>"CU","label_fr"=>"Cuba","label_en"=>"Cuba"},
{"rec_id\nISO 3166 alpha2"=>"CV","label_fr"=>"Cape verde","label_en"=>"Cap-Vert"},
{"rec_id\nISO 3166 alpha2"=>"CX","label_fr"=>"Christmas Island","label_en"=>"Île Christmas"},
{"rec_id\nISO 3166 alpha2"=>"CY","label_fr"=>"Cyprus","label_en"=>"Chypre"},
{"rec_id\nISO 3166 alpha2"=>"CZ","label_fr"=>"Czech Republic (The)","label_en"=>"République tchèque"},
{"rec_id\nISO 3166 alpha2"=>"DE","label_fr"=>"Germany","label_en"=>"Allemagne"},
{"rec_id\nISO 3166 alpha2"=>"DJ","label_fr"=>"Djibouti","label_en"=>"Djibouti"},
{"rec_id\nISO 3166 alpha2"=>"DK","label_fr"=>"Denmark","label_en"=>"Danemark"},
{"rec_id\nISO 3166 alpha2"=>"DM","label_fr"=>"Dominica","label_en"=>"Dominique"},
{"rec_id\nISO 3166 alpha2"=>"DO","label_fr"=>"Dominican Republic (The)","label_en"=>"Dominicaine, République"},
{"rec_id\nISO 3166 alpha2"=>"DZ","label_fr"=>"Algeria","label_en"=>"Algérie"},
{"rec_id\nISO 3166 alpha2"=>"EC","label_fr"=>"Ecuador","label_en"=>"Equateur"},
{"rec_id\nISO 3166 alpha2"=>"EE","label_fr"=>"Estonia","label_en"=>"Estonie"},
{"rec_id\nISO 3166 alpha2"=>"EG","label_fr"=>"Egypt","label_en"=>"Egypte"},
{"rec_id\nISO 3166 alpha2"=>"EH","label_fr"=>"Western Sahara","label_en"=>"Sahara occidental"},
{"rec_id\nISO 3166 alpha2"=>"ER","label_fr"=>"Eritrea","label_en"=>"Erythrée"},
{"rec_id\nISO 3166 alpha2"=>"ES","label_fr"=>"Spain","label_en"=>"Espagne"},
{"rec_id\nISO 3166 alpha2"=>"ET","label_fr"=>"Ethiopia","label_en"=>"Ethiopie"},
{"rec_id\nISO 3166 alpha2"=>"FI","label_fr"=>"Finland","label_en"=>"Finlande"},
{"rec_id\nISO 3166 alpha2"=>"FJ","label_fr"=>"Fiji","label_en"=>"Fidji"},
{"rec_id\nISO 3166 alpha2"=>"FK","label_fr"=>"Falkland Islands (Malvinas)","label_en"=>"Îles Malouines (Falkland)"},
{"rec_id\nISO 3166 alpha2"=>"FM","label_fr"=>"Micronesia, Federated States of","label_en"=>"Micronésie"},
{"rec_id\nISO 3166 alpha2"=>"FO","label_fr"=>"Faroe Islands","label_en"=>"Îles Féroé"},
{"rec_id\nISO 3166 alpha2"=>"FR","label_fr"=>"France","label_en"=>"France"},
{"rec_id\nISO 3166 alpha2"=>"GA","label_fr"=>"Gabon","label_en"=>"Gabon"},
{"rec_id\nISO 3166 alpha2"=>"GB","label_fr"=>"United Kingdom (The)","label_en"=>"Royaume-Uni"},
{"rec_id\nISO 3166 alpha2"=>"GD","label_fr"=>"Grenada","label_en"=>"Grenade"},
{"rec_id\nISO 3166 alpha2"=>"GE","label_fr"=>"Georgia","label_en"=>"Géorgie"},
{"rec_id\nISO 3166 alpha2"=>"GF","label_fr"=>"French Guiana","label_en"=>"Guyane"},
{"rec_id\nISO 3166 alpha2"=>"GG","label_fr"=>"Guernsey","label_en"=>"Guernesey"},
{"rec_id\nISO 3166 alpha2"=>"GH","label_fr"=>"Ghana","label_en"=>"Ghana"},
{"rec_id\nISO 3166 alpha2"=>"GI","label_fr"=>"Gibraltar","label_en"=>"Gibraltar"},
{"rec_id\nISO 3166 alpha2"=>"GL","label_fr"=>"Greenland","label_en"=>"Groenland"},
{"rec_id\nISO 3166 alpha2"=>"GM","label_fr"=>"Gambia (The)","label_en"=>"Gambie"},
{"rec_id\nISO 3166 alpha2"=>"GN","label_fr"=>"Guinea","label_en"=>"Guinée"},
{"rec_id\nISO 3166 alpha2"=>"GP","label_fr"=>"Guadeloupe","label_en"=>"Guadeloupe"},
{"rec_id\nISO 3166 alpha2"=>"GQ","label_fr"=>"Equatorial Guinea","label_en"=>"Guinée Equatoriale"},
{"rec_id\nISO 3166 alpha2"=>"GR","label_fr"=>"Greece","label_en"=>"Grèce"},
{"rec_id\nISO 3166 alpha2"=>"GS","label_fr"=>"South Georgia and the South Sandwich Islands","label_en"=>"Géorgie du Sud et les îles Sandwich du Sud"},
{"rec_id\nISO 3166 alpha2"=>"GT","label_fr"=>"Guatemala","label_en"=>"Guatemala"},
{"rec_id\nISO 3166 alpha2"=>"GU","label_fr"=>"Guam","label_en"=>"Guam"},
{"rec_id\nISO 3166 alpha2"=>"GW","label_fr"=>"Guinea-Bissau","label_en"=>"Guinée-Bissau"},
{"rec_id\nISO 3166 alpha2"=>"GY","label_fr"=>"Guyana","label_en"=>"Guyana"},
{"rec_id\nISO 3166 alpha2"=>"HK","label_fr"=>"Hong Kong","label_en"=>"Hong Kong"},
{"rec_id\nISO 3166 alpha2"=>"HM","label_fr"=>"Heard Island and McDonald Islands","label_en"=>"Île Heard et îles McDonald"},
{"rec_id\nISO 3166 alpha2"=>"HN","label_fr"=>"Honduras","label_en"=>"Honduras"},
{"rec_id\nISO 3166 alpha2"=>"HR","label_fr"=>"Croatia","label_en"=>"Croatie"},
{"rec_id\nISO 3166 alpha2"=>"HT","label_fr"=>"Haiti","label_en"=>"Haïti"},
{"rec_id\nISO 3166 alpha2"=>"HU","label_fr"=>"Hungary","label_en"=>"Hongrie"},
{"rec_id\nISO 3166 alpha2"=>"ID","label_fr"=>"Indonesia","label_en"=>"Indonésie"},
{"rec_id\nISO 3166 alpha2"=>"IE","label_fr"=>"Ireland","label_en"=>"Irlande"},
{"rec_id\nISO 3166 alpha2"=>"IL","label_fr"=>"Israel","label_en"=>"Israël"},
{"rec_id\nISO 3166 alpha2"=>"IM","label_fr"=>"Isle of Man","label_en"=>"Île de Man"},
{"rec_id\nISO 3166 alpha2"=>"IN","label_fr"=>"India","label_en"=>"Inde"},
{"rec_id\nISO 3166 alpha2"=>"IO","label_fr"=>"British Indian Ocean Territory","label_en"=>"Territoire britannique de l'océan Indien"},
{"rec_id\nISO 3166 alpha2"=>"IQ","label_fr"=>"Iraq","label_en"=>"Iraq"},
{"rec_id\nISO 3166 alpha2"=>"IR","label_fr"=>"Iran, Islamic Republic of","label_en"=>"Iran"},
{"rec_id\nISO 3166 alpha2"=>"IS","label_fr"=>"Iceland","label_en"=>"Islande"},
{"rec_id\nISO 3166 alpha2"=>"IT","label_fr"=>"Italy","label_en"=>"Italie"},
{"rec_id\nISO 3166 alpha2"=>"JE","label_fr"=>"Jersey","label_en"=>"Jersey"},
{"rec_id\nISO 3166 alpha2"=>"JM","label_fr"=>"Jamaica","label_en"=>"Jamaïque"},
{"rec_id\nISO 3166 alpha2"=>"JO","label_fr"=>"Jordan","label_en"=>"Jordanie"},
{"rec_id\nISO 3166 alpha2"=>"JP","label_fr"=>"Japan","label_en"=>"Japon"},
{"rec_id\nISO 3166 alpha2"=>"KE","label_fr"=>"Kenya","label_en"=>"Kenya"},
{"rec_id\nISO 3166 alpha2"=>"KG","label_fr"=>"Kyrgyzstan","label_en"=>"Kirghizistan"},
{"rec_id\nISO 3166 alpha2"=>"KH","label_fr"=>"Cambodia","label_en"=>"Cambodge"},
{"rec_id\nISO 3166 alpha2"=>"KI","label_fr"=>"Kiribati","label_en"=>"Kiribati"},
{"rec_id\nISO 3166 alpha2"=>"KM","label_fr"=>"Comoros","label_en"=>"Comores"},
{"rec_id\nISO 3166 alpha2"=>"KN","label_fr"=>"Saint Kitts and Nevis","label_en"=>"Saint-Christophe-et-Niévès"},
{"rec_id\nISO 3166 alpha2"=>"KP","label_fr"=>"Korea, Democratic People's Republic of","label_en"=>"Corée du Nord"},
{"rec_id\nISO 3166 alpha2"=>"KR","label_fr"=>"Korea, Republic of","label_en"=>"Corée du Sud"},
{"rec_id\nISO 3166 alpha2"=>"KW","label_fr"=>"Kuwait","label_en"=>"Koweït"},
{"rec_id\nISO 3166 alpha2"=>"KY","label_fr"=>"Cayman Islands","label_en"=>"Îles Caïmanes"},
{"rec_id\nISO 3166 alpha2"=>"KZ","label_fr"=>"Kazakhstan","label_en"=>"Kazakhstan"},
{"rec_id\nISO 3166 alpha2"=>"LA","label_fr"=>"Lao People's Democratic Republic","label_en"=>"Laos"},
{"rec_id\nISO 3166 alpha2"=>"LB","label_fr"=>"Lebanon","label_en"=>"Liban"},
{"rec_id\nISO 3166 alpha2"=>"LC","label_fr"=>"Saint Lucia","label_en"=>"Sainte-Lucie"},
{"rec_id\nISO 3166 alpha2"=>"LI","label_fr"=>"Liechtenstein","label_en"=>"Liechtenstein"},
{"rec_id\nISO 3166 alpha2"=>"LK","label_fr"=>"Sri Lanka","label_en"=>"Sri Lanka"},
{"rec_id\nISO 3166 alpha2"=>"LR","label_fr"=>"Liberia","label_en"=>"Liberia"},
{"rec_id\nISO 3166 alpha2"=>"LS","label_fr"=>"Lesotho","label_en"=>"Lesotho"},
{"rec_id\nISO 3166 alpha2"=>"LT","label_fr"=>"Lithuania","label_en"=>"Lituanie"},
{"rec_id\nISO 3166 alpha2"=>"LU","label_fr"=>"Luxembourg","label_en"=>"Luxembourg"},
{"rec_id\nISO 3166 alpha2"=>"LV","label_fr"=>"Latvia","label_en"=>"Lettonie"},
{"rec_id\nISO 3166 alpha2"=>"LY","label_fr"=>"Libyan Arab Jamahiriya","label_en"=>"Libye"},
{"rec_id\nISO 3166 alpha2"=>"MA","label_fr"=>"Morocco","label_en"=>"Maroc"},
{"rec_id\nISO 3166 alpha2"=>"MC","label_fr"=>"Monaco","label_en"=>"Monaco"},
{"rec_id\nISO 3166 alpha2"=>"MD","label_fr"=>"Moldova, Republic of","label_en"=>"Moldavie, République de"},
{"rec_id\nISO 3166 alpha2"=>"ME","label_fr"=>"Montenegro","label_en"=>"Monténégro"},
{"rec_id\nISO 3166 alpha2"=>"MG","label_fr"=>"Madagascar","label_en"=>"Madagascar"},
{"rec_id\nISO 3166 alpha2"=>"MH","label_fr"=>"Marshall islands (The)","label_en"=>"Marshall"},
{"rec_id\nISO 3166 alpha2"=>"MK","label_fr"=>"Macedonia, the Former Yugoslav Republic of","label_en"=>"Macédoine"},
{"rec_id\nISO 3166 alpha2"=>"ML","label_fr"=>"Mali","label_en"=>"Mali"},
{"rec_id\nISO 3166 alpha2"=>"MM","label_fr"=>"Myanmar (Burma)","label_en"=>"Myanmar (Birmanie)"},
{"rec_id\nISO 3166 alpha2"=>"MN","label_fr"=>"Mongolia","label_en"=>"Mongolie"},
{"rec_id\nISO 3166 alpha2"=>"MO","label_fr"=>"Macao","label_en"=>"Macao"},
{"rec_id\nISO 3166 alpha2"=>"MP","label_fr"=>"Northern Mariana Islands","label_en"=>"îles Mariannes du Nord"},
{"rec_id\nISO 3166 alpha2"=>"MQ","label_fr"=>"Martinique","label_en"=>"Martinique"},
{"rec_id\nISO 3166 alpha2"=>"MR","label_fr"=>"Mauritania","label_en"=>"Mauritanie"},
{"rec_id\nISO 3166 alpha2"=>"MS","label_fr"=>"Montserrat","label_en"=>"Montserrat"},
{"rec_id\nISO 3166 alpha2"=>"MT","label_fr"=>"Malta","label_en"=>"Malte"},
{"rec_id\nISO 3166 alpha2"=>"MU","label_fr"=>"Mauritius","label_en"=>"Maurice"},
{"rec_id\nISO 3166 alpha2"=>"MV","label_fr"=>"Maldives","label_en"=>"Maldives"},
{"rec_id\nISO 3166 alpha2"=>"MW","label_fr"=>"Malawi","label_en"=>"Malawi"},
{"rec_id\nISO 3166 alpha2"=>"MX","label_fr"=>"Mexico","label_en"=>"Mexique"},
{"rec_id\nISO 3166 alpha2"=>"MY","label_fr"=>"Malaysia","label_en"=>"Malaisie"},
{"rec_id\nISO 3166 alpha2"=>"MZ","label_fr"=>"Mozambique","label_en"=>"Mozambique"},
{"rec_id\nISO 3166 alpha2"=>"NA","label_fr"=>"Namibia","label_en"=>"Namibie"},
{"rec_id\nISO 3166 alpha2"=>"NC","label_fr"=>"New Caledonia","label_en"=>"ouvelle-Calédonie"},
{"rec_id\nISO 3166 alpha2"=>"NE","label_fr"=>"Niger (The)","label_en"=>"Niger"},
{"rec_id\nISO 3166 alpha2"=>"NF","label_fr"=>"Norfolk Island","label_en"=>"Norfolk"},
{"rec_id\nISO 3166 alpha2"=>"NG","label_fr"=>"Nigeria","label_en"=>"Nigeria"},
{"rec_id\nISO 3166 alpha2"=>"NI","label_fr"=>"Nicaragua","label_en"=>"Nicaragua"},
{"rec_id\nISO 3166 alpha2"=>"NL","label_fr"=>"Netherlands (The)","label_en"=>"Pays-Bas"},
{"rec_id\nISO 3166 alpha2"=>"NO","label_fr"=>"Norway","label_en"=>"Norvège"},
{"rec_id\nISO 3166 alpha2"=>"NP","label_fr"=>"Nepal","label_en"=>"Népal"},
{"rec_id\nISO 3166 alpha2"=>"NR","label_fr"=>"Nauru","label_en"=>"Nauru"},
{"rec_id\nISO 3166 alpha2"=>"NU","label_fr"=>"Niue","label_en"=>"Niué"},
{"rec_id\nISO 3166 alpha2"=>"NZ","label_fr"=>"New Zealand","label_en"=>"Nouvelle-Zélande"},
{"rec_id\nISO 3166 alpha2"=>"OM","label_fr"=>"Oman","label_en"=>"Oman"},
{"rec_id\nISO 3166 alpha2"=>"PA","label_fr"=>"Panama","label_en"=>"Panama"},
{"rec_id\nISO 3166 alpha2"=>"PE","label_fr"=>"Peru","label_en"=>"Pérou"},
{"rec_id\nISO 3166 alpha2"=>"PF","label_fr"=>"French Polynesia","label_en"=>"Polynésie française"},
{"rec_id\nISO 3166 alpha2"=>"PG","label_fr"=>"Papua New Guinea","label_en"=>"Papouasie-Nouvelle Guinée"},
{"rec_id\nISO 3166 alpha2"=>"PH","label_fr"=>"Philippines (The)","label_en"=>"Philippines"},
{"rec_id\nISO 3166 alpha2"=>"PK","label_fr"=>"Pakistan","label_en"=>"Pakistan"},
{"rec_id\nISO 3166 alpha2"=>"PL","label_fr"=>"Poland","label_en"=>"Pologne"},
{"rec_id\nISO 3166 alpha2"=>"PM","label_fr"=>"Saint Pierre and Miquelon","label_en"=>"Saint-Pierre-et-Miquelon"},
{"rec_id\nISO 3166 alpha2"=>"PN","label_fr"=>"Pitcairn","label_en"=>"Pitcairn"},
{"rec_id\nISO 3166 alpha2"=>"PR","label_fr"=>"Puerto Rico","label_en"=>"Porto Rico"},
{"rec_id\nISO 3166 alpha2"=>"PS","label_fr"=>"Palestinian Territory, Occupied","label_en"=>"Palestine"},
{"rec_id\nISO 3166 alpha2"=>"PT","label_fr"=>"Portugal","label_en"=>"Portugal"},
{"rec_id\nISO 3166 alpha2"=>"PW","label_fr"=>"Palau","label_en"=>"Palaos"},
{"rec_id\nISO 3166 alpha2"=>"PY","label_fr"=>"Paraguay","label_en"=>"Paraguay"},
{"rec_id\nISO 3166 alpha2"=>"QA","label_fr"=>"Qatar","label_en"=>"Qatar"},
{"rec_id\nISO 3166 alpha2"=>"RE","label_fr"=>"Réunion","label_en"=>"Réunion"},
{"rec_id\nISO 3166 alpha2"=>"RO","label_fr"=>"Romania","label_en"=>"Roumanie"},
{"rec_id\nISO 3166 alpha2"=>"RS","label_fr"=>"Serbia","label_en"=>"Serbie"},
{"rec_id\nISO 3166 alpha2"=>"RU","label_fr"=>"Russian Federation","label_en"=>"Russie"},
{"rec_id\nISO 3166 alpha2"=>"RW","label_fr"=>"Rwanda","label_en"=>"Rwanda"},
{"rec_id\nISO 3166 alpha2"=>"SA","label_fr"=>"Saudi Arabia","label_en"=>"Arabie Saoudite"},
{"rec_id\nISO 3166 alpha2"=>"SB","label_fr"=>"Solomon Islands","label_en"=>"Îles Salomon"},
{"rec_id\nISO 3166 alpha2"=>"SC","label_fr"=>"Seychelles","label_en"=>"Seychelles"},
{"rec_id\nISO 3166 alpha2"=>"SD","label_fr"=>"Sudan","label_en"=>"Soudan"},
{"rec_id\nISO 3166 alpha2"=>"SE","label_fr"=>"Sweden","label_en"=>"Suède"},
{"rec_id\nISO 3166 alpha2"=>"SG","label_fr"=>"Singapore","label_en"=>"Singapour"},
{"rec_id\nISO 3166 alpha2"=>"SH","label_fr"=>"Saint Helena","label_en"=>"Sainte-Hélène, île"},
{"rec_id\nISO 3166 alpha2"=>"SI","label_fr"=>"Slovenia","label_en"=>"Slovénie"},
{"rec_id\nISO 3166 alpha2"=>"SJ","label_fr"=>"Svalbard and Jan Mayen","label_en"=>"Svalbard et île Jan Mayen"},
{"rec_id\nISO 3166 alpha2"=>"SK","label_fr"=>"Slovakia","label_en"=>"Slovaquie"},
{"rec_id\nISO 3166 alpha2"=>"SL","label_fr"=>"Sierra Leone","label_en"=>"Sierra Leone"},
{"rec_id\nISO 3166 alpha2"=>"SM","label_fr"=>"San Marino","label_en"=>"Saint-Marin"},
{"rec_id\nISO 3166 alpha2"=>"SN","label_fr"=>"Senegal","label_en"=>"Sénégal"},
{"rec_id\nISO 3166 alpha2"=>"SO","label_fr"=>"Somalia","label_en"=>"Somalie"},
{"rec_id\nISO 3166 alpha2"=>"SR","label_fr"=>"Suriname","label_en"=>"Suriname"},
{"rec_id\nISO 3166 alpha2"=>"ST","label_fr"=>"Sao Tome and Principe","label_en"=>"Sao Tomé-et-Principe"},
{"rec_id\nISO 3166 alpha2"=>"SV","label_fr"=>"El Salvador","label_en"=>"Salvador"},
{"rec_id\nISO 3166 alpha2"=>"SY","label_fr"=>"Syrian Arab Republic","label_en"=>"Syrie"},
{"rec_id\nISO 3166 alpha2"=>"SZ","label_fr"=>"Swaziland","label_en"=>"Swaziland"},
{"rec_id\nISO 3166 alpha2"=>"TC","label_fr"=>"Turks and Caicos Islands","label_en"=>"Îles Turques et Caïques"},
{"rec_id\nISO 3166 alpha2"=>"TD","label_fr"=>"Chad","label_en"=>"Tchad"},
{"rec_id\nISO 3166 alpha2"=>"TF","label_fr"=>"French Southern Territories","label_en"=>"Terres australes et antarctiques françaises"},
{"rec_id\nISO 3166 alpha2"=>"TG","label_fr"=>"Togo","label_en"=>"Togo"},
{"rec_id\nISO 3166 alpha2"=>"TH","label_fr"=>"Thailand","label_en"=>"Thaïlande"},
{"rec_id\nISO 3166 alpha2"=>"TJ","label_fr"=>"Tajikistan","label_en"=>"Tadjikistan"},
{"rec_id\nISO 3166 alpha2"=>"TK","label_fr"=>"Tokelau","label_en"=>"Tokelau"},
{"rec_id\nISO 3166 alpha2"=>"TL","label_fr"=>"Timor-Leste","label_en"=>"Timor oriental"},
{"rec_id\nISO 3166 alpha2"=>"TM","label_fr"=>"Turkmenistan","label_en"=>"Turkméistan"},
{"rec_id\nISO 3166 alpha2"=>"TN","label_fr"=>"Tunisia","label_en"=>"Tunisie"},
{"rec_id\nISO 3166 alpha2"=>"TO","label_fr"=>"Tonga","label_en"=>"Tonga"},
{"rec_id\nISO 3166 alpha2"=>"TR","label_fr"=>"Turkey","label_en"=>"Turquie"},
{"rec_id\nISO 3166 alpha2"=>"TT","label_fr"=>"Trinidad and Tobago","label_en"=>"Trinité-et-Tobago"},
{"rec_id\nISO 3166 alpha2"=>"TV","label_fr"=>"Tuvalu","label_en"=>"Tuvalu"},
{"rec_id\nISO 3166 alpha2"=>"TW","label_fr"=>"Taiwan, Province of China","label_en"=>"Taïwan / (République de Chine)"},
{"rec_id\nISO 3166 alpha2"=>"TZ","label_fr"=>"Tanzania, United Reprublic of","label_en"=>"Tanzanie"},
{"rec_id\nISO 3166 alpha2"=>"UA","label_fr"=>"Ukraine","label_en"=>"Ukraine"},
{"rec_id\nISO 3166 alpha2"=>"UG","label_fr"=>"Uganda","label_en"=>"Ouganda"},
{"rec_id\nISO 3166 alpha2"=>"UM","label_fr"=>"United States Minor Outlying Islands","label_en"=>"Îles mineures éloignées des États-Unis"},
{"rec_id\nISO 3166 alpha2"=>"US","label_fr"=>"United States (The)","label_en"=>"Etats-Unis"},
{"rec_id\nISO 3166 alpha2"=>"UY","label_fr"=>"Uruguay","label_en"=>"Uruguay"},
{"rec_id\nISO 3166 alpha2"=>"UZ","label_fr"=>"Uzbekistan","label_en"=>"Ouzbékistan"},
{"rec_id\nISO 3166 alpha2"=>"VA","label_fr"=>"Holy See (The)","label_en"=>"Vatican / (Saint-Siège)"},
{"rec_id\nISO 3166 alpha2"=>"VC","label_fr"=>"Saint Vincent and the Grenadines","label_en"=>"Saint-Vincent-et-les-Grenadines"},
{"rec_id\nISO 3166 alpha2"=>"VE","label_fr"=>"Venezuela","label_en"=>"Venezuela"},
{"rec_id\nISO 3166 alpha2"=>"VG","label_fr"=>"Virgin Islands, British","label_en"=>"Îles Vierges britanniques"},
{"rec_id\nISO 3166 alpha2"=>"VI","label_fr"=>"Virgin Islands, U.S.","label_en"=>"Îles Vierges américaines"},
{"rec_id\nISO 3166 alpha2"=>"VN","label_fr"=>"Viet Nam","label_en"=>"Viêt Nam"},
{"rec_id\nISO 3166 alpha2"=>"VU","label_fr"=>"Vanuatu","label_en"=>"Vanuatu"},
{"rec_id\nISO 3166 alpha2"=>"WF","label_fr"=>"Wallis and Futuna","label_en"=>"Wallis-et-Futuna"},
{"rec_id\nISO 3166 alpha2"=>"WS","label_fr"=>"Samoa, Western","label_en"=>"Samoa Occidentales"},
{"rec_id\nISO 3166 alpha2"=>"YE","label_fr"=>"Yemen","label_en"=>"Yémen"},
{"rec_id\nISO 3166 alpha2"=>"YT","label_fr"=>"Mayotte","label_en"=>"Mayotte"},
{"rec_id\nISO 3166 alpha2"=>"ZA","label_fr"=>"South Africa","label_en"=>"Afrique du Sud"},
{"rec_id\nISO 3166 alpha2"=>"ZM","label_fr"=>"Zambia","label_en"=>"Zambie"},
{"rec_id\nISO 3166 alpha2"=>"ZW","label_fr"=>"Zimbabwe","label_en"=>"Zimbabwe"},
{"rec_id\nISO 3166 alpha2"=>"ZZ","label_fr"=>"Multiple country","label_en"=>"Pays multiples"}]

