require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrgunitsController do

  # This should return the minimal set of attributes required to create a valid
  # Orgunit. As you add validations to Orgunit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrgunitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all orgunits as @orgunits" do
      orgunit = Orgunit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:orgunits).should eq([orgunit])
    end
  end

  describe "GET show" do
    it "assigns the requested orgunit as @orgunit" do
      orgunit = Orgunit.create! valid_attributes
      get :show, {:id => orgunit.to_param}, valid_session
      assigns(:orgunit).should eq(orgunit)
    end
  end

  describe "GET new" do
    it "assigns a new orgunit as @orgunit" do
      get :new, {}, valid_session
      assigns(:orgunit).should be_a_new(Orgunit)
    end
  end

  describe "GET edit" do
    it "assigns the requested orgunit as @orgunit" do
      orgunit = Orgunit.create! valid_attributes
      get :edit, {:id => orgunit.to_param}, valid_session
      assigns(:orgunit).should eq(orgunit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Orgunit" do
        expect {
          post :create, {:orgunit => valid_attributes}, valid_session
        }.to change(Orgunit, :count).by(1)
      end

      it "assigns a newly created orgunit as @orgunit" do
        post :create, {:orgunit => valid_attributes}, valid_session
        assigns(:orgunit).should be_a(Orgunit)
        assigns(:orgunit).should be_persisted
      end

      it "redirects to the created orgunit" do
        post :create, {:orgunit => valid_attributes}, valid_session
        response.should redirect_to(Orgunit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved orgunit as @orgunit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orgunit.any_instance.stub(:save).and_return(false)
        post :create, {:orgunit => {  }}, valid_session
        assigns(:orgunit).should be_a_new(Orgunit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orgunit.any_instance.stub(:save).and_return(false)
        post :create, {:orgunit => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested orgunit" do
        orgunit = Orgunit.create! valid_attributes
        # Assuming there are no other orgunits in the database, this
        # specifies that the Orgunit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Orgunit.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => orgunit.to_param, :orgunit => { "these" => "params" }}, valid_session
      end

      it "assigns the requested orgunit as @orgunit" do
        orgunit = Orgunit.create! valid_attributes
        put :update, {:id => orgunit.to_param, :orgunit => valid_attributes}, valid_session
        assigns(:orgunit).should eq(orgunit)
      end

      it "redirects to the orgunit" do
        orgunit = Orgunit.create! valid_attributes
        put :update, {:id => orgunit.to_param, :orgunit => valid_attributes}, valid_session
        response.should redirect_to(orgunit)
      end
    end

    describe "with invalid params" do
      it "assigns the orgunit as @orgunit" do
        orgunit = Orgunit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orgunit.any_instance.stub(:save).and_return(false)
        put :update, {:id => orgunit.to_param, :orgunit => {  }}, valid_session
        assigns(:orgunit).should eq(orgunit)
      end

      it "re-renders the 'edit' template" do
        orgunit = Orgunit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orgunit.any_instance.stub(:save).and_return(false)
        put :update, {:id => orgunit.to_param, :orgunit => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested orgunit" do
      orgunit = Orgunit.create! valid_attributes
      expect {
        delete :destroy, {:id => orgunit.to_param}, valid_session
      }.to change(Orgunit, :count).by(-1)
    end

    it "redirects to the orgunits list" do
      orgunit = Orgunit.create! valid_attributes
      delete :destroy, {:id => orgunit.to_param}, valid_session
      response.should redirect_to(orgunits_url)
    end
  end

end
